"""ORM models.

Every model is re-exported here so that Alembic's ``env.py`` and
``Base.metadata`` see the complete schema via a single import. A model missing
from this list is invisible to autogenerate: its table would never be created
and ``alembic check`` would report no drift while the table simply does not
exist.
"""

from app.db.base import Base, TimestampMixin, UUIDPrimaryKeyMixin
from app.models.activity import ActivityLog
from app.models.analytics import DailyMetric
from app.models.audit import AuditEvent, AuditLog
from app.models.career import (
    DEFAULT_CAREER_EVIDENCE_SOURCE,
    CareerEvidence,
    CareerExperience,
    CareerProfile,
)
from app.models.developer import (
    DEFAULT_GIT_SCAN_STATUS,
    GitBranch,
    GitCommit,
    GitRepository,
    GitScanRun,
)
from app.models.enums import (
    ActivityEvent,
    CalendarEventType,
    CareerEvidenceType,
    CareerRecordKind,
    EvidenceStrength,
    GitScanStatus,
    KnowledgeEntityType,
    KnowledgeLinkType,
    LearningActivityType,
    LearningGoalStatus,
    NoteStatus,
    ProjectPriority,
    ProjectStatus,
    RecommendationPriority,
    RecommendationStatus,
    RecommendationType,
    ResourceType,
    RiskSeverity,
    RiskStatus,
    RiskType,
    SkillLevelSource,
    TaskPriority,
    TaskStatus,
)
from app.models.knowledge import (
    DEFAULT_KNOWLEDGE_LINK_TYPE,
    DEFAULT_NOTE_STATUS,
    DEFAULT_RESOURCE_TYPE,
    MAX_REVISIONS_PER_NOTE,
    Bookmark,
    Category,
    Concept,
    Document,
    KnowledgeLink,
    Note,
    NoteRevision,
    Resource,
    concept_tags,
    note_tags,
)
from app.models.learning import (
    DEFAULT_LEARNING_GOAL_PRIORITY,
    DEFAULT_LEARNING_GOAL_STATUS,
    DEFAULT_SKILL_CURRENT_LEVEL,
    DEFAULT_SKILL_LEVEL_SOURCE,
    DEFAULT_SKILL_TARGET_LEVEL,
    MAX_SKILL_LEVEL,
    MIN_SKILL_LEVEL,
    LearningActivity,
    LearningGoal,
    Skill,
)
from app.models.password_reset import PasswordResetToken
from app.models.planner import (
    DEFAULT_CALENDAR_EVENT_TYPE,
    DEFAULT_WORK_SESSION_STATUS,
    AvailabilityRule,
    CalendarEvent,
    WorkSession,
    WorkSessionStatus,
)
from app.models.project import DEFAULT_PROJECT_PRIORITY, DEFAULT_PROJECT_STATUS, Project
from app.models.risk import (
    DEFAULT_RECOMMENDATION_PRIORITY,
    DEFAULT_RECOMMENDATION_STATUS,
    DEFAULT_RISK_SEVERITY,
    DEFAULT_RISK_STATUS,
    Recommendation,
    Risk,
    RiskEvaluation,
)
from app.models.session import Session
from app.models.tag import Tag, project_tags, task_tags
from app.models.task import (
    DEFAULT_TASK_PRIORITY,
    DEFAULT_TASK_STATUS,
    Task,
    TaskDependency,
)
from app.models.user import DEFAULT_ROLE, User, UserRole

__all__ = [
    "DEFAULT_CALENDAR_EVENT_TYPE",
    "DEFAULT_CAREER_EVIDENCE_SOURCE",
    "DEFAULT_GIT_SCAN_STATUS",
    "DEFAULT_KNOWLEDGE_LINK_TYPE",
    "DEFAULT_LEARNING_GOAL_PRIORITY",
    "DEFAULT_LEARNING_GOAL_STATUS",
    "DEFAULT_NOTE_STATUS",
    "DEFAULT_PROJECT_PRIORITY",
    "DEFAULT_PROJECT_STATUS",
    "DEFAULT_RECOMMENDATION_PRIORITY",
    "DEFAULT_RECOMMENDATION_STATUS",
    "DEFAULT_RESOURCE_TYPE",
    "DEFAULT_RISK_SEVERITY",
    "DEFAULT_RISK_STATUS",
    "DEFAULT_ROLE",
    "DEFAULT_SKILL_CURRENT_LEVEL",
    "DEFAULT_SKILL_LEVEL_SOURCE",
    "DEFAULT_SKILL_TARGET_LEVEL",
    "DEFAULT_TASK_PRIORITY",
    "DEFAULT_TASK_STATUS",
    "DEFAULT_WORK_SESSION_STATUS",
    "MAX_REVISIONS_PER_NOTE",
    "MAX_SKILL_LEVEL",
    "MIN_SKILL_LEVEL",
    "ActivityEvent",
    "ActivityLog",
    "AuditEvent",
    "AuditLog",
    "AvailabilityRule",
    "Base",
    "Bookmark",
    "CalendarEvent",
    "CalendarEventType",
    "CareerEvidence",
    "CareerEvidenceType",
    "CareerExperience",
    "CareerProfile",
    "CareerRecordKind",
    "Category",
    "Concept",
    "DailyMetric",
    "Document",
    "EvidenceStrength",
    "GitBranch",
    "GitCommit",
    "GitRepository",
    "GitScanRun",
    "GitScanStatus",
    "KnowledgeEntityType",
    "KnowledgeLink",
    "KnowledgeLinkType",
    "LearningActivity",
    "LearningActivityType",
    "LearningGoal",
    "LearningGoalStatus",
    "Note",
    "NoteRevision",
    "NoteStatus",
    "PasswordResetToken",
    "Project",
    "ProjectPriority",
    "ProjectStatus",
    "Recommendation",
    "RecommendationPriority",
    "RecommendationStatus",
    "RecommendationType",
    "Resource",
    "ResourceType",
    "Risk",
    "RiskEvaluation",
    "RiskSeverity",
    "RiskStatus",
    "RiskType",
    "Session",
    "Skill",
    "SkillLevelSource",
    "Tag",
    "Task",
    "TaskDependency",
    "TaskPriority",
    "TaskStatus",
    "TimestampMixin",
    "UUIDPrimaryKeyMixin",
    "User",
    "UserRole",
    "WorkSession",
    "WorkSessionStatus",
    "concept_tags",
    "note_tags",
    "project_tags",
    "task_tags",
]
