export type {
  ApiErrorBody,
  ApiErrorCode,
  ApiErrorEnvelope,
  AuthSession,
  DatabaseStatus,
  HealthResponse,
  HealthStatus,
  ISODateTimeString,
  LoginPayload,
  PasswordChangePayload,
  PasswordResetConfirmPayload,
  PasswordResetRequestPayload,
  PasswordResetRequestedResponse,
  PermissionString,
  ProfileUpdatePayload,
  RefreshPayload,
  RegisterPayload,
  RootHealthResponse,
  SessionListResponse,
  TokenPair,
  User,
  UserDeletionPayload,
  UserRole,
  UUIDString,
} from './api'

export type { PageMeta, Paginated, PaginationParams } from './pagination'

export {
  ANALYTICS_CSV_DATASETS,
  ANALYTICS_TREND_METRICS,
  DEFAULT_WINDOW_PRESET,
  MAX_ANALYTICS_RANGE_DAYS,
  WINDOW_PRESETS,
  formatRangeLabel,
  isDateOnly,
  isWindowPreset,
  parseDateOnly,
  rangeDays,
  resolveWindow,
  shiftDays,
  toDateOnly,
  todayDateOnly,
} from './analytics'
export type {
  AnalyticsCsvDataset,
  AnalyticsListParams,
  AnalyticsRange,
  ComparisonTotal,
  ConsistencyRead,
  CsvExportManifestRead,
  DailyMetricRead,
  DeadlineAdherenceRead,
  EstimationAccuracyRead,
  FocusRead,
  Granularity,
  KnowledgeAnalyticsRead,
  LearningAnalyticsRead,
  MetricRange,
  OverdueTaskRead,
  OverviewRead,
  ProductivityRead,
  ProjectAnalyticsRead,
  RebuildRead,
  ScoreComponent,
  TagCount,
  TagCountRead,
  TaskAnalyticsRead,
  TimeBucketRead,
  TimeDistributionRead,
  TimeSlice,
  TrendMetric,
  TrendPoint,
  VelocityRead,
  WindowPreset,
  WindowPresetId,
  WorkloadRead,
} from './analytics'

export {
  KNOWLEDGE_ENTITY_META,
  KNOWLEDGE_ENTITY_TYPES,
  KNOWLEDGE_LINK_TYPES,
  LINK_TYPE_META,
  NOTE_STATUS_META,
  NOTE_STATUSES,
  RESOURCE_TYPES,
  RESOURCE_TYPE_META,
  formatKnowledgeDate,
  formatKnowledgeDateTime,
  formatRelative,
  renderMarkdown,
  summarise,
} from './knowledge'
export type {
  BacklinkParams,
  BacklinksResponse,
  Bookmark,
  BookmarkCreatePayload,
  BookmarkListParams,
  BookmarkUpdatePayload,
  CategoryCreatePayload,
  CategoryListParams,
  CategoryUpdatePayload,
  Concept,
  ConceptCreatePayload,
  ConceptListParams,
  ConceptUpdatePayload,
  Document,
  DocumentCreatePayload,
  DocumentListParams,
  DocumentUpdatePayload,
  GraphParams,
  KnowledgeCategory,
  KnowledgeEntityType,
  KnowledgeGraph,
  KnowledgeGraphEdge,
  KnowledgeGraphNode,
  KnowledgeLink,
  KnowledgeLinkCreatePayload,
  KnowledgeLinkType,
  KnowledgeSearchResult,
  Note,
  NoteCreatePayload,
  NoteListParams,
  NoteRevision,
  NoteStatus,
  NoteUpdatePayload,
  OutboundLinkParams,
  Resource,
  ResourceCreatePayload,
  ResourceListParams,
  ResourceType,
  ResourceUpdatePayload,
  SearchParams,
} from './knowledge'

export {
  CONFLICT_KIND_META,
  CONFLICT_SEVERITY_META,
  EVENT_TYPE_META,
  WEEKDAY_LABELS,
  WORK_SESSION_STATUS_META,
  formatPlannerInstant,
  formatPlannerMinutes,
  formatPlannerRatio,
} from './planner'
export type {
  AvailabilityReplacementPayload,
  AvailabilityRule,
  AvailabilityRuleInput,
  AvailabilityWeek,
  CalendarEvent,
  CalendarEventCreatePayload,
  CalendarEventListParams,
  CalendarEventType,
  CalendarEventUpdatePayload,
  Conflict,
  ConflictKind,
  ConflictList,
  ConflictListParams,
  ConflictSeverity,
  DateOnlyString,
  PlannerDay,
  PlannerListParams,
  PlannerMonth,
  PlannerSlot,
  PlannerSuggestion,
  PlannerView,
  PlannerWeek,
  PlannerWindow,
  SuggestionRequest,
  SuggestionResponse,
  WeekTotals,
  WorkSession,
  WorkSessionCreatePayload,
  WorkSessionListParams,
  WorkSessionStatus,
  WorkSessionUpdatePayload,
} from './planner'

export { PRIORITY_META, PROJECT_STATUS_META, TASK_STATUS_META, TASK_STATUS_ORDER } from './work'
export type {
  ActivityEvent,
  ActivityListParams,
  ActivityPage,
  ActivityStats,
  DateOnlyString as WorkDateOnlyString,
  Project,
  ProjectCreatePayload,
  ProjectListParams,
  ProjectPage,
  ProjectPriority,
  ProjectStats,
  ProjectStatus,
  ProjectSummary,
  ProjectTaskListParams,
  ProjectUpdatePayload,
  SortOrder,
  StatusMeta,
  StatusTone,
  TagAssignmentPayload,
  TagListParams,
  TagPage,
  Task,
  TaskCreatePayload,
  TaskListParams,
  TaskPage,
  TaskPriority,
  TaskStats,
  TaskStatus,
  TaskStatusChangePayload,
  TaskSummary,
  TaskUpdatePayload,
  WorkEventType,
  WorkTag,
} from './work'

// Phase 7. Re-exported like every other feature's types so consumers reach them
// from the barrel rather than importing `@/types/risk` directly — the risk
// vocabulary is a set of frozen arrays as well as derived types, so the
// constants are re-exported by value and the rest as types.
export {
  EVIDENCE_STRENGTHS,
  OPEN_RECOMMENDATION_STATUSES,
  RECOMMENDATION_PRIORITIES,
  RECOMMENDATION_STATUSES,
  RECOMMENDATION_TYPES,
  RISK_SEVERITIES,
  RISK_STATUSES,
  RISK_TYPES,
} from './risk'
export type {
  EvaluationListParams,
  EvaluationParams,
  EvaluationRead,
  EvidenceStrength,
  RecommendationListParams,
  RecommendationListRead,
  RecommendationPriority,
  RecommendationRead,
  RecommendationStatus,
  RecommendationSummaryRead,
  RecommendationType,
  RiskEvidenceRead,
  RiskListParams,
  RiskListRead,
  RiskRead,
  RiskSeverity,
  RiskStatus,
  RiskSummaryRead,
  RiskType,
} from './risk'
